### ISSUE TITLE
User Story 1: Create a note

### ISSUE THREAD

**Issue by FatimaHad** [CMU-17313Q/nodebb-f24-gaurdiansofthegit#5]
**As an** Instructor, **I want** to be able to create a note in announcements page  that does not need a reply, **so that** I would just notify them and not allow a further discussion on the post. 

           **Impact** : High -Gives the instructor the authority to create a post that does not allow students further reply or discuss it. 
           
           **Effort** : Medium - requires a button that posts the message as a “note” and the post page would not have a reply choice. 

Split of the work to git this User story work 
- adding a button that makes the post in type of note and showing it in the announcement page.
- modify the file so that when posting the type note, it will not allow anyone to reply on the post.
- Creating a nite type announcement should be working fully, through testing.

NOTE: This user story depends on user story 2 being functional and seamlessly integrated first. This is so that we can also consider anonymous posting for notes.

**Comment by SarimFaraz** [comment]
We were unable to implement this feature because of time constraints. We prioritized implementing anonymous posts and navigation shortcuts and could not find the time to get this done in sprint 1.
